### ISSUE TITLE
Add Makefile with Cosmos standard targets

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/ethermint_bak#12]
Ideally we can just reuse the one from `cosmos-sdk`?

**Comment by alexanderbez** [comment]
We can leverage certain targets yeah, but I don't think we should copy-pasta.

**Comment by greg-szabo** [comment]
I'd start with copy-paste + modifications for this thing, so any of our current developers can easily come over. This was a huge pain in cosmos-sdk automation too until it was harmonized. The ones I see as beneficial:
build*
test*
get_*
update_tools
localnet-*

Also the `networks/` folder (and Makefile in there) should be implemented here too.
Is this something you want me to work on?

**Comment by jackzampolin** [comment]
@greg-szabo I can handle this stuff. My thoughts are similar on `Makefile` targets being consistent cross repo. Does that sound good to you @alexanderbez?

**Comment by alexanderbez** [comment]
Yeah, I'm on board with that @greg-szabo, but if possible, can we have the targets base dash-cased please?

**Comment by jackzampolin** [comment]
I'm also pro `-` instead of `_`

**Comment by greg-szabo** [comment]
I don't have a preference (I used to, and different systems taught me differently... I'm looking at you AWS tags that switch dashes to underscores when converted from a hostname, because of reasons... And you C# that prefer to start internal function names with an underscore for convenience and readability, but keep using camelcase otherwise for reasons... And you, JSON/JS, who love dashes so much that you turn camelcase into dashes too when translating from higher level languages... And you Ansible, that doesn't accept Yaml templates with dashes in some cases, but underscore seems ok...) All in all, I don't have a preference anymore.

I'd rather have an exact same setup as all other repos, but this is your repo, the decision is yours.

You could also convince the others to use dashes... Just saying... (I just noticed that I used dashes too in my Makefile targets. The underscores come from earlier developers.)

**Comment by alexanderbez** [comment]
Closed via #21
